// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';


function make(id, data) {
  return {
          _RE: "Organization",
          id: id,
          seq: 0,
          data: data
        };
}

exports.make = make;
/* No side effect */
