// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Caml_obj = require("rescript/lib/js/caml_obj.js");
var Belt_Array = require("rescript/lib/js/belt_Array.js");

function make(id, data) {
  return {
          id: id,
          state: data !== undefined ? ({
                TAG: /* Free */0,
                _0: data
              }) : undefined
        };
}

function transition(t, $$event) {
  var match = t.state;
  var id = t.id;
  if ($$event.TAG === /* Created */0) {
    return {
            TAG: /* Ok */0,
            _0: {
              id: id,
              state: {
                TAG: /* Free */0,
                _0: $$event.data
              }
            }
          };
  }
  if (match === undefined) {
    return {
            TAG: /* Error */1,
            _0: {
              TAG: /* Uninitialized */0,
              _0: id
            }
          };
  }
  if (match.TAG !== /* Free */0) {
    return {
            TAG: /* Error */1,
            _0: {
              TAG: /* Locked */1,
              _0: id
            }
          };
  }
  var data = match._0;
  switch ($$event.TAG | 0) {
    case /* SectionAdded */1 :
        return {
                TAG: /* Ok */0,
                _0: {
                  id: id,
                  state: {
                    TAG: /* Free */0,
                    _0: {
                      title: data.title,
                      sections: Belt_Array.concat(data.sections, [$$event.section]),
                      tags: data.tags,
                      owner: data.owner,
                      responsibility: data.responsibility
                    }
                  }
                }
              };
    case /* SectionDeleted */2 :
        var deleted = $$event.section;
        return {
                TAG: /* Ok */0,
                _0: {
                  id: id,
                  state: {
                    TAG: /* Free */0,
                    _0: {
                      title: data.title,
                      sections: Belt_Array.keep(data.sections, (function (id) {
                              return Caml_obj.notequal(id, deleted);
                            })),
                      tags: data.tags,
                      owner: data.owner,
                      responsibility: data.responsibility
                    }
                  }
                }
              };
    case /* ResponsibilityAssigned */3 :
        return {
                TAG: /* Ok */0,
                _0: {
                  id: id,
                  state: {
                    TAG: /* Free */0,
                    _0: {
                      title: data.title,
                      sections: data.sections,
                      tags: data.tags,
                      owner: data.owner,
                      responsibility: $$event.responsibility
                    }
                  }
                }
              };
    case /* TagsModified */4 :
        return {
                TAG: /* Ok */0,
                _0: {
                  id: id,
                  state: {
                    TAG: /* Free */0,
                    _0: {
                      title: data.title,
                      sections: data.sections,
                      tags: $$event.tags,
                      owner: data.owner,
                      responsibility: data.responsibility
                    }
                  }
                }
              };
    case /* Locked */5 :
        return {
                TAG: /* Ok */0,
                _0: {
                  id: id,
                  state: {
                    TAG: /* Locked */1,
                    by: $$event.by,
                    data: data
                  }
                }
              };
    
  }
}

function create(t, date, data) {
  var $$event = {
    TAG: /* Created */0,
    date: date,
    data: data
  };
  return [
          transition(t, $$event),
          [$$event]
        ];
}

function addSection(t, date, section) {
  var $$event = {
    TAG: /* SectionAdded */1,
    date: date,
    section: section
  };
  return [
          transition(t, $$event),
          [$$event]
        ];
}

function deleteSection(t, date, section) {
  var $$event = {
    TAG: /* SectionDeleted */2,
    date: date,
    section: section
  };
  return [
          transition(t, $$event),
          [$$event]
        ];
}

function assignResponsibility(t, date, responsibility) {
  var $$event = {
    TAG: /* ResponsibilityAssigned */3,
    date: date,
    responsibility: responsibility
  };
  return [
          transition(t, $$event),
          [$$event]
        ];
}

function modifyTags(t, date, tags) {
  var $$event = {
    TAG: /* TagsModified */4,
    date: date,
    tags: tags
  };
  return [
          transition(t, $$event),
          [$$event]
        ];
}

function lock(t, date, by) {
  var $$event = {
    TAG: /* Locked */5,
    date: date,
    by: by
  };
  return [
          transition(t, $$event),
          [$$event]
        ];
}

var Command = {
  create: create,
  addSection: addSection,
  deleteSection: deleteSection,
  assignResponsibility: assignResponsibility,
  modifyTags: modifyTags,
  lock: lock
};

var Id;

var SectionId;

var UserId;

exports.Id = Id;
exports.SectionId = SectionId;
exports.UserId = UserId;
exports.make = make;
exports.transition = transition;
exports.Command = Command;
/* No side effect */
