// Generated by ReScript, PLEASE EDIT WITH CARE


function make(id, data) {
  return {
          id: id,
          data: data
        };
}

var Id;

var OrganizationId;

export {
  Id ,
  OrganizationId ,
  make ,
}
/* No side effect */
