// Generated by ReScript, PLEASE EDIT WITH CARE


function make(id, data) {
  return {
          id: id,
          state: data !== undefined ? ({
                TAG: /* Anonymous */1,
                data: data
              }) : undefined
        };
}

export {
  make ,
}
/* No side effect */
