// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';


function transition(t, $$event) {
  return {
          TAG: /* Ok */0,
          _0: {
            id: t.id,
            data: $$event.data
          }
        };
}

function make(id, data) {
  return {
          id: id,
          data: data
        };
}

function create(t, date, data) {
  var $$event = /* Created */{
    date: date,
    data: data
  };
  return [
          transition(t, $$event),
          [$$event]
        ];
}

var Command = {
  create: create
};

var Id;

var OrganizationId;

exports.Id = Id;
exports.OrganizationId = OrganizationId;
exports.transition = transition;
exports.make = make;
exports.Command = Command;
/* No side effect */
