// Generated by ReScript, PLEASE EDIT WITH CARE


function make(id, data) {
  return {
          id: id,
          state: data !== undefined ? ({
                TAG: /* Free */0,
                _0: data
              }) : undefined
        };
}

export {
  make ,
}
/* No side effect */
