// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';


function toString(t) {
  return t;
}

function fromString(str) {
  return str;
}

exports.toString = toString;
exports.fromString = fromString;
/* No side effect */
