// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';


var $$Document;

var Orginization;

var Revision;

var Section;

var User;

var Version;

var Webhook;

var Session;

exports.$$Document = $$Document;
exports.Orginization = Orginization;
exports.Revision = Revision;
exports.Section = Section;
exports.User = User;
exports.Version = Version;
exports.Webhook = Webhook;
exports.Session = Session;
/* No side effect */
