// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';


function make(id, state, seqOpt, param) {
  var seq = seqOpt !== undefined ? seqOpt : 0;
  return {
          _RE: "Session",
          id: id,
          seq: seq,
          events: [],
          state: state
        };
}

exports.make = make;
/* No side effect */
