// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Curry = require("rescript/lib/js/curry.js");
var Framework = require("../Framework.bs.js");
var Belt_Array = require("rescript/lib/js/belt_Array.js");
var Council_Entity_Session = require("./Council_Entity_Session.bs.js");

var Transition = Framework.Transition.Make(Council_Entity_Session);

function transition(t, $$event) {
  var match = t.state;
  var events = t.events;
  var seq = t.seq;
  var id = t.id;
  var _RE = t._RE;
  if (match !== undefined) {
    if ($$event.TAG === /* Created */0) {
      return {
              TAG: /* Error */1,
              _0: {
                TAG: /* AlreadyInitialized */2,
                id: id
              }
            };
    } else if (match.TAG === /* Member */0) {
      return {
              TAG: /* Error */1,
              _0: {
                TAG: /* AlreadyConnected */3,
                id: id,
                exist: match.member,
                newed: $$event.member
              }
            };
    } else {
      return {
              TAG: /* Ok */0,
              _0: {
                _RE: _RE,
                id: id,
                seq: seq,
                events: Belt_Array.concat(events, [$$event]),
                state: {
                  TAG: /* Member */0,
                  member: $$event.member,
                  data: match.data
                }
              }
            };
    }
  } else if ($$event.TAG === /* Created */0) {
    return {
            TAG: /* Ok */0,
            _0: {
              _RE: _RE,
              id: id,
              seq: seq,
              events: Belt_Array.concat(events, [$$event]),
              state: {
                TAG: /* Anonymous */1,
                data: $$event.data
              }
            }
          };
  } else {
    return {
            TAG: /* Error */1,
            _0: {
              TAG: /* Uninitialized */1,
              id: id
            }
          };
  }
}

function create(t, date, data) {
  return Curry._3(Transition.run, transition, t, {
              TAG: /* Created */0,
              date: date,
              data: data
            });
}

function createWithUser(t, date, data, member) {
  var event1 = {
    TAG: /* Created */0,
    date: date,
    data: data
  };
  var event2 = {
    TAG: /* MemberConnected */1,
    date: date,
    member: member
  };
  return Curry._3(Transition.runMany, transition, t, [
              event1,
              event2
            ]);
}

function connectUser(t, date, member) {
  return Curry._3(Transition.run, transition, t, {
              TAG: /* MemberConnected */1,
              date: date,
              member: member
            });
}

exports.Transition = Transition;
exports.transition = transition;
exports.create = create;
exports.createWithUser = createWithUser;
exports.connectUser = connectUser;
/* Transition Not a pure module */
