// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';


function make(id, data) {
  return {
          id: id,
          data: data
        };
}

var Id;

var UserId;

exports.Id = Id;
exports.UserId = UserId;
exports.make = make;
/* No side effect */
