// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Framework = require("../Framework.bs.js");
var Belt_Array = require("rescript/lib/js/belt_Array.js");
var Council_Entity_Member = require("./Council_Entity_Member.bs.js");

var Transition = Framework.Transition.Make(Council_Entity_Member);

function transition(t, $$event) {
  if ($$event.TAG === /* Created */0) {
    return {
            TAG: /* Ok */0,
            _0: {
              _RE: t._RE,
              id: t.id,
              seq: t.seq,
              events: Belt_Array.concat(t.events, [$$event]),
              state: $$event.data
            }
          };
  } else {
    return {
            TAG: /* Error */1,
            _0: /* Invariant */0
          };
  }
}

function create(t, date, data) {
  var $$event = {
    TAG: /* Created */0,
    date: date,
    data: data
  };
  return [
          transition(t, $$event),
          [$$event]
        ];
}

exports.Transition = Transition;
exports.transition = transition;
exports.create = create;
/* Transition Not a pure module */
