// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Curry from "rescript/lib/es6/curry.js";
import * as Belt_Array from "rescript/lib/es6/belt_Array.js";
import * as Belt_Result from "rescript/lib/es6/belt_Result.js";

function Make(Type) {
  return Type;
}

var Entity = {
  Make: Make
};

function Make$1(Entity) {
  var run = function (t, entity, $$event) {
    return [
            Curry._2(t, entity, $$event),
            [$$event]
          ];
  };
  var runMany = function (t, entity, $$event) {
    var next = Belt_Array.reduce($$event, {
          TAG: /* Ok */0,
          _0: entity
        }, (function (prev, $$event) {
            return Belt_Result.flatMap(prev, (function (__x) {
                          return Curry._2(t, __x, $$event);
                        }));
          }));
    return [
            next,
            $$event
          ];
  };
  return {
          run: run,
          runMany: runMany
        };
}

var Transition = {
  Make: Make$1
};

function Make$2(Entity) {
  return {};
}

var Repository = {
  Make: Make$2
};

export {
  Entity ,
  Transition ,
  Repository ,
}
/* No side effect */
