// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Curry = require("rescript/lib/js/curry.js");
var Belt_Array = require("rescript/lib/js/belt_Array.js");
var Belt_Result = require("rescript/lib/js/belt_Result.js");

function Make(Type) {
  return Type;
}

var Entity = {
  Make: Make
};

function Make$1(Entity) {
  var run = function (t, entity, $$event) {
    return Curry._2(t, entity, $$event);
  };
  var runMany = function (t, entity, events) {
    return Belt_Array.reduce(events, {
                TAG: /* Ok */0,
                _0: entity
              }, (function (prev, $$event) {
                  return Belt_Result.flatMap(prev, (function (__x) {
                                return Curry._2(t, __x, $$event);
                              }));
                }));
  };
  return {
          run: run,
          runMany: runMany
        };
}

var Transition = {
  Make: Make$1
};

function Make$2(Config) {
  return {};
}

var Repository = {
  Make: Make$2
};

exports.Entity = Entity;
exports.Transition = Transition;
exports.Repository = Repository;
/* No side effect */
