// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Curry = require("rescript/lib/js/curry.js");
var Belt_Array = require("rescript/lib/js/belt_Array.js");
var Belt_Result = require("rescript/lib/js/belt_Result.js");

function run(t, s, ev) {
  return [
          Curry._2(t, s, ev),
          [ev]
        ];
}

function runMany(t, s, ev) {
  var next = Belt_Array.reduce(ev, {
        TAG: /* Ok */0,
        _0: s
      }, (function (prev, ev) {
          return Belt_Result.flatMap(prev, (function (__x) {
                        return Curry._2(t, __x, ev);
                      }));
        }));
  return [
          next,
          ev
        ];
}

exports.run = run;
exports.runMany = runMany;
/* No side effect */
