// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Framework = require("../Framework.bs.js");
var Council_Entity_Member = require("../Entity/Council_Entity_Member.bs.js");

Framework.Repository.Make({
      Entity: Council_Entity_Member
    });

var Entity;

var Logic;

exports.Entity = Entity;
exports.Logic = Logic;
/*  Not a pure module */
