// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Framework = require("../Framework.bs.js");
var Council_Entity_Session = require("../Entity/Council_Entity_Session.bs.js");

Framework.Repository.Make({
      Entity: Council_Entity_Session
    });

var Entity;

var Logic;

exports.Entity = Entity;
exports.Logic = Logic;
/*  Not a pure module */
