// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Curry from "rescript/lib/es6/curry.js";
import * as Framework from "../Framework.bs.js";
import * as Council_Entity_Session from "../Entity/Council_Entity_Session.bs.js";
import * as Council_Command_Session from "../Command/Council_Command_Session.bs.js";

Framework.Repository.Make(Council_Entity_Session);

async function find(t, id) {
  var entity = Council_Entity_Session.make(id, undefined);
  var match = await Curry._2(t.eventStream, id, 0);
  var events = match[0];
  if (events.length === 0) {
    return ;
  }
  var match$1 = Curry._3(Council_Command_Session.Transition.runMany, Council_Command_Session.transition, entity, events);
  var entity$1 = match$1[0];
  if (entity$1.TAG === /* Ok */0) {
    return entity$1._0;
  }
  
}

var Entity;

var Command;

export {
  Entity ,
  Command ,
  find ,
}
/*  Not a pure module */
