// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Id from "./Id.bs.js";

var Id$1 = Id.Make({});

function make(id, data) {
  return {
          id: id,
          data: data
        };
}

function transition(t, $$event) {
  return {
          TAG: /* Ok */0,
          _0: {
            id: t.id,
            data: $$event.data
          }
        };
}

function create(t, date, data) {
  var $$event = /* Created */{
    date: date,
    data: data
  };
  return [
          transition(t, $$event),
          [$$event]
        ];
}

var Command = {
  create: create
};

var Organization;

export {
  Organization ,
  Id$1 as Id,
  make ,
  transition ,
  Command ,
}
/* Id Not a pure module */
