// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Curry from "rescript/lib/es6/curry.js";
import * as Belt_Array from "rescript/lib/es6/belt_Array.js";
import * as Belt_Result from "rescript/lib/es6/belt_Result.js";

function run(t, s, ev) {
  return [
          Curry._2(t, s, ev),
          [ev]
        ];
}

function runMany(t, s, ev) {
  var next = Belt_Array.reduce(ev, {
        TAG: /* Ok */0,
        _0: s
      }, (function (prev, ev) {
          return Belt_Result.flatMap(prev, (function (__x) {
                        return Curry._2(t, __x, ev);
                      }));
        }));
  return [
          next,
          ev
        ];
}

export {
  run ,
  runMany ,
}
/* No side effect */
