// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Framework from "../Framework.bs.js";
import * as Council_Entity_Member from "../Entity/Council_Entity_Member.bs.js";

var Transition = Framework.Transition.Make(Council_Entity_Member);

function transition(t, $$event) {
  return {
          TAG: /* Ok */0,
          _0: {
            id: t.id,
            data: $$event.data
          }
        };
}

function create(t, date, data) {
  var $$event = /* Created */{
    date: date,
    data: data
  };
  return [
          transition(t, $$event),
          [$$event]
        ];
}

var Member;

export {
  Member ,
  Transition ,
  transition ,
  create ,
}
/* Transition Not a pure module */
