// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Curry from "rescript/lib/es6/curry.js";
import * as Caml_obj from "rescript/lib/es6/caml_obj.js";
import * as Framework from "../Framework.bs.js";
import * as Belt_Array from "rescript/lib/es6/belt_Array.js";
import * as Council_Entity_Document from "../Entity/Council_Entity_Document.bs.js";

var Transition = Framework.Transition.Make({
      make: Council_Entity_Document.make
    });

function transition(t, $$event) {
  var match = t.state;
  var id = t.id;
  if ($$event.TAG === /* Created */0) {
    return {
            TAG: /* Ok */0,
            _0: {
              id: id,
              state: {
                TAG: /* Free */0,
                _0: $$event.data
              }
            }
          };
  }
  if (match === undefined) {
    return {
            TAG: /* Error */1,
            _0: {
              TAG: /* Uninitialized */0,
              _0: id
            }
          };
  }
  if (match.TAG !== /* Free */0) {
    return {
            TAG: /* Error */1,
            _0: {
              TAG: /* Locked */1,
              _0: id
            }
          };
  }
  var data = match._0;
  switch ($$event.TAG | 0) {
    case /* SectionAdded */1 :
        return {
                TAG: /* Ok */0,
                _0: {
                  id: id,
                  state: {
                    TAG: /* Free */0,
                    _0: {
                      title: data.title,
                      sections: Belt_Array.concat(data.sections, [$$event.section]),
                      tags: data.tags,
                      owner: data.owner,
                      responsibility: data.responsibility
                    }
                  }
                }
              };
    case /* SectionDeleted */2 :
        var deleted = $$event.section;
        return {
                TAG: /* Ok */0,
                _0: {
                  id: id,
                  state: {
                    TAG: /* Free */0,
                    _0: {
                      title: data.title,
                      sections: Belt_Array.keep(data.sections, (function (id) {
                              return Caml_obj.notequal(id, deleted);
                            })),
                      tags: data.tags,
                      owner: data.owner,
                      responsibility: data.responsibility
                    }
                  }
                }
              };
    case /* ResponsibilityAssigned */3 :
        return {
                TAG: /* Ok */0,
                _0: {
                  id: id,
                  state: {
                    TAG: /* Free */0,
                    _0: {
                      title: data.title,
                      sections: data.sections,
                      tags: data.tags,
                      owner: data.owner,
                      responsibility: $$event.responsibility
                    }
                  }
                }
              };
    case /* TagsModified */4 :
        return {
                TAG: /* Ok */0,
                _0: {
                  id: id,
                  state: {
                    TAG: /* Free */0,
                    _0: {
                      title: data.title,
                      sections: data.sections,
                      tags: $$event.tags,
                      owner: data.owner,
                      responsibility: data.responsibility
                    }
                  }
                }
              };
    case /* Locked */5 :
        return {
                TAG: /* Ok */0,
                _0: {
                  id: id,
                  state: {
                    TAG: /* Locked */1,
                    by: $$event.by,
                    data: data
                  }
                }
              };
    
  }
}

function create(t, date, data) {
  var $$event = {
    TAG: /* Created */0,
    date: date,
    data: data
  };
  return Curry._3(Transition.run, transition, t, $$event);
}

function addSection(t, date, section) {
  var $$event = {
    TAG: /* SectionAdded */1,
    date: date,
    section: section
  };
  return Curry._3(Transition.run, transition, t, $$event);
}

function deleteSection(t, date, section) {
  var $$event = {
    TAG: /* SectionDeleted */2,
    date: date,
    section: section
  };
  return Curry._3(Transition.run, transition, t, $$event);
}

function assignResponsibility(t, date, responsibility) {
  var $$event = {
    TAG: /* ResponsibilityAssigned */3,
    date: date,
    responsibility: responsibility
  };
  return Curry._3(Transition.run, transition, t, $$event);
}

function modifyTags(t, date, tags) {
  var $$event = {
    TAG: /* TagsModified */4,
    date: date,
    tags: tags
  };
  return Curry._3(Transition.run, transition, t, $$event);
}

function lock(t, date, by) {
  var $$event = {
    TAG: /* Locked */5,
    date: date,
    by: by
  };
  return Curry._3(Transition.run, transition, t, $$event);
}

var $$Document;

export {
  $$Document ,
  Transition ,
  transition ,
  create ,
  addSection ,
  deleteSection ,
  assignResponsibility ,
  modifyTags ,
  lock ,
}
/* Transition Not a pure module */
