// Generated by ReScript, PLEASE EDIT WITH CARE


function make(id, data) {
  return {
          id: id,
          data: data
        };
}

function transition(t, $$event) {
  return {
          TAG: /* Ok */0,
          _0: {
            id: t.id,
            data: $$event.data
          }
        };
}

function create(t, date, data) {
  var $$event = /* Created */{
    date: date,
    data: data
  };
  return [
          transition(t, $$event),
          [$$event]
        ];
}

var Command = {
  create: create
};

var Id;

var OrganizationId;

export {
  Id ,
  OrganizationId ,
  make ,
  transition ,
  Command ,
}
/* No side effect */
