// Generated by ReScript, PLEASE EDIT WITH CARE


var $$Document;

var Orginization;

var Revision;

var Section;

var User;

var Version;

var Webhook;

var Session;

export {
  $$Document ,
  Orginization ,
  Revision ,
  Section ,
  User ,
  Version ,
  Webhook ,
  Session ,
}
/* No side effect */
