// Generated by ReScript, PLEASE EDIT WITH CARE


function make(id, data) {
  return {
          id: id,
          state: data !== undefined ? ({
                TAG: /* Free */0,
                _0: data
              }) : undefined
        };
}

function transition(t, $$event) {
  var match = t.state;
  var id = t.id;
  if ($$event.TAG === /* Created */0) {
    return {
            TAG: /* Ok */0,
            _0: {
              id: id,
              state: $$event.state
            }
          };
  }
  if (match === undefined) {
    return {
            TAG: /* Error */1,
            _0: {
              TAG: /* Uninitialized */0,
              _0: id
            }
          };
  }
  if (match.TAG !== /* Free */0) {
    return {
            TAG: /* Error */1,
            _0: {
              TAG: /* Locked */1,
              _0: id
            }
          };
  }
  var data = match._0;
  switch ($$event.TAG | 0) {
    case /* HeadingModified */1 :
        return {
                TAG: /* Ok */0,
                _0: {
                  id: id,
                  state: {
                    TAG: /* Free */0,
                    _0: {
                      heading: $$event.heading,
                      body: data.body,
                      tags: data.tags
                    }
                  }
                }
              };
    case /* BodyModified */2 :
        return {
                TAG: /* Ok */0,
                _0: {
                  id: id,
                  state: {
                    TAG: /* Free */0,
                    _0: {
                      heading: data.heading,
                      body: $$event.body,
                      tags: data.tags
                    }
                  }
                }
              };
    case /* TagsModified */3 :
        return {
                TAG: /* Ok */0,
                _0: {
                  id: id,
                  state: {
                    TAG: /* Free */0,
                    _0: {
                      heading: data.heading,
                      body: data.body,
                      tags: $$event.tags
                    }
                  }
                }
              };
    case /* Locked */4 :
        return {
                TAG: /* Ok */0,
                _0: {
                  id: id,
                  state: {
                    TAG: /* Locked */1,
                    by: $$event.by,
                    data: data
                  }
                }
              };
    
  }
}

function create(t, date, state) {
  var $$event = {
    TAG: /* Created */0,
    date: date,
    state: state
  };
  return [
          transition(t, $$event),
          [$$event]
        ];
}

function modifyHeading(t, date, heading) {
  var $$event = {
    TAG: /* HeadingModified */1,
    date: date,
    heading: heading
  };
  return [
          transition(t, $$event),
          [$$event]
        ];
}

function modifyBody(t, date, body) {
  var $$event = {
    TAG: /* BodyModified */2,
    date: date,
    body: body
  };
  return [
          transition(t, $$event),
          [$$event]
        ];
}

function modifyTags(t, date, tags) {
  var $$event = {
    TAG: /* TagsModified */3,
    date: date,
    tags: tags
  };
  return [
          transition(t, $$event),
          [$$event]
        ];
}

function lock(t, date, by) {
  var $$event = {
    TAG: /* Locked */4,
    date: date,
    by: by
  };
  return [
          transition(t, $$event),
          [$$event]
        ];
}

var Command = {
  create: create,
  modifyHeading: modifyHeading,
  modifyBody: modifyBody,
  modifyTags: modifyTags,
  lock: lock
};

var Id;

var UserId;

export {
  Id ,
  UserId ,
  make ,
  transition ,
  Command ,
}
/* No side effect */
