// Generated by ReScript, PLEASE EDIT WITH CARE


function make(id, state) {
  return {
          id: id,
          state: state
        };
}

function transition(t, $$event) {
  var state = t.state;
  var id = t.id;
  if ($$event.TAG === /* Created */0) {
    return {
            TAG: /* Ok */0,
            _0: {
              id: id,
              state: $$event.state
            }
          };
  }
  if (state === undefined) {
    return {
            TAG: /* Error */1,
            _0: /* Uninitialized */{
              _0: id
            }
          };
  }
  switch ($$event.TAG | 0) {
    case /* HeadingModified */1 :
        return {
                TAG: /* Ok */0,
                _0: {
                  id: id,
                  state: {
                    heading: $$event.heading,
                    body: state.body,
                    tags: state.tags
                  }
                }
              };
    case /* BodyModified */2 :
        return {
                TAG: /* Ok */0,
                _0: {
                  id: id,
                  state: {
                    heading: state.heading,
                    body: $$event.body,
                    tags: state.tags
                  }
                }
              };
    case /* TagsModified */3 :
        return {
                TAG: /* Ok */0,
                _0: {
                  id: id,
                  state: {
                    heading: state.heading,
                    body: state.body,
                    tags: $$event.tags
                  }
                }
              };
    
  }
}

function create(t, date, state) {
  var $$event = {
    TAG: /* Created */0,
    date: date,
    state: state
  };
  return [
          transition(t, $$event),
          [$$event]
        ];
}

function modifyHeading(t, date, heading) {
  var $$event = {
    TAG: /* HeadingModified */1,
    date: date,
    heading: heading
  };
  return [
          transition(t, $$event),
          [$$event]
        ];
}

function modifyBody(t, date, body) {
  var $$event = {
    TAG: /* BodyModified */2,
    date: date,
    body: body
  };
  return [
          transition(t, $$event),
          [$$event]
        ];
}

function modifyTags(t, date, tags) {
  var $$event = {
    TAG: /* TagsModified */3,
    date: date,
    tags: tags
  };
  return [
          transition(t, $$event),
          [$$event]
        ];
}

var Command = {
  create: create,
  modifyHeading: modifyHeading,
  modifyBody: modifyBody,
  modifyTags: modifyTags
};

var Id;

export {
  Id ,
  make ,
  transition ,
  Command ,
}
/* No side effect */
