// Generated by ReScript, PLEASE EDIT WITH CARE


function make(id, state) {
  return {
          id: id,
          state: state
        };
}

function transition(t, $$event) {
  return {
          TAG: /* Ok */0,
          _0: {
            id: t.id,
            state: $$event.state
          }
        };
}

function create(t, date, state) {
  var $$event = /* Created */{
    date: date,
    state: state
  };
  return [
          transition(t, $$event),
          [$$event]
        ];
}

var Command = {
  create: create
};

var Id;

var OrganizationId;

export {
  Id ,
  OrganizationId ,
  make ,
  transition ,
  Command ,
}
/* No side effect */
