// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';


function make(memberRepo, sessionRepo) {
  return {
          memberRepo: memberRepo,
          sessionRepo: sessionRepo
        };
}

exports.make = make;
/* No side effect */
